{% set name = "gcp-correction" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/gcp/archive/v{{ version }}.tar.gz
  sha256: 26c4d889062412c377459a4a939cbe12527dcdc5d89c99cf607f589ec86c5fe4

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - mctc-gcp --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Geometrical Counter-Poise Correction
  dev_url: https://github.com/grimme-lab/gcp

extra:
  recipe-maintainers:
    - awvwgk
