{% set name = "gcp-correction" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/gcp/archive/v{{ version }}.tar.gz
  sha256: 30ffee1406054dd69a30b9e1c6ed7fd79fc0c0fb173a6d8170b4b7b303435e42

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson >=0.51
    - meson <0.56
    - ninja
    - asciidoctor
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]


test:
  commands:
    - mctc-gcp --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
  summary: Geometrical Counter-Poise Correction
  dev_url: https://github.com/grimme-lab/gcp

extra:
  recipe-maintainers:
    - awvwgk
