{% set name = "gcp-correction" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/gcp/archive/v{{ version }}.tar.gz
  sha256: f8bb203c5af57e942c3f02967d1970b2fdcfcd2bb8fc60b999c8b4226324a730
  patches:
    - wrap.patch

build:
  number: 1
  script:
    - set -ex  # [unix]
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
    - meson setup _build --prefix=%PREFIX% --libdir=lib --pkg-config-path=%PREFIX%\lib\pkgconfig  # [win]
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - asciidoctor  # [unix]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - mctc-lib
  run:
    - {{ pin_compatible('mctc-lib', max_pin='x.x') }}


test:
  commands:
    - mctc-gcp --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Geometrical Counter-Poise Correction
  dev_url: https://github.com/grimme-lab/gcp

extra:
  recipe-maintainers:
    - awvwgk
